### PR TITLE
Fix incorrect /pub opening alerts

### PR DESCRIPTION
**Pull request by jabbink**
Foundation /pub has no online presence and the old URL has been taken offline, resulting in continuous spam about a broken iCal feed, every Wednesday, Thursday and Friday at 4pm

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Is there a replacement for this feature?

**Comment by jabbink** [comment]
After repeatedly asking for a replacement online schedule, and not getting any response, I guess there is no (online) schedule anymore (or any schedule at all as some bartenders of the foundation itself were surprised when there were suddenly three events at once some weeks ago).

**Review by TimvdLippe — APPROVED** [review]
That's really unfortunate news. Sad to see this go, but it is the appropriate decision given the situation :cry:

**Comment by jabbink** [comment]
Just found this promise, though
image

**Comment by jabbink** [comment]
They did indeed suddenly filled the old planning site.

**Pull request closed without merging**
