### PR TITLE
Decaffeinate all script files

### PR DESCRIPTION
**Pull request by TimvdLippe**
Since ES6 landed, most of the coffeescript special syntax
is incorporated in EcmaScript itself. Using ES6,
contributing to this project becomes easier,
as ES6 is more well-known than coffeescript.

I have tested this PR with several files and everything appears to be working. There was no test suite available, so I am not 100% sure if this is actually the case :wink:

### CODE REVIEW

**Comment by praseodym** [comment]
Does ES6 work on Node.js 4.8.2?

**Comment by TimvdLippe** [comment]
Ah, per http://node.green/ that appears to be (probably) true. Not sure how to test it, as I am running the latest version of Node :stuck_out_tongue:

**Comment by praseodym** [comment]
Try the Dockerfile 😉 

Feel free to update the Dockerfile as needed. The only requirement we have is that the CH CA must be trusted by Node.

**Comment by TimvdLippe** [comment]
@praseodym All right, done! I tested by building the Docker image and then run `docker run -it --rm <version> bash` and in there run `florrie /r/programmerhumor` and it worked :smile:

**Comment by praseodym** [comment]
I think we might be better off basing the Dockerfile on `node:carbon` and then [adding the CA certificate](https://github.com/WISVCH/docker-debian/blob/master/stretch/Dockerfile). Either way, node will need to be started with `--use-openssl-ca`.

**Comment by TimvdLippe** [comment]
@praseodym Done! Based of `node:8` per https://github.com/nodejs/docker-node

**Comment by praseodym** [comment]
I think we're still stuck with Node not accepting the CH CA?

**Comment by TimvdLippe** [comment]
I copied the content of https://github.com/WISVCH/docker-debian/blob/master/stretch/Dockerfile so I am not sure what else needs to be done to fix it?

**Comment by praseodym** [comment]
> Either way, node will need to be started with `--use-openssl-ca`.

**Comment by TimvdLippe** [comment]
Well, that was "fun". All dependencies are now decaffeinated as well. I had to point to the github repos though, as most of the packages are not published. Will create PRs for all of them.

**Comment by TimvdLippe** [comment]
All packages that have been deprecated are removed. This PR is now only blocked on https://github.com/jabbink/hubot-plusplus-improved/pull/1 Other than that this is ready for review!

**Comment by jabbink** [comment]
Okay, I'll look at it this weekend. Pinky promise.

**Comment by TimvdLippe** [comment]
This PR is now ready for review/merge

**Pull request merged**
